src/AudioProcessing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.my_view, name="login"),
    path("rec", views.record, name="record"),
    path("save", views.save, name="save"),
    path("student", views.Student_reg, name="student"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("logout", views.logout_view, name="logout"),
]

src/SpeakerIndetification/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("AudioProcessing.urls"))
]

src/AudioProcessing/models.py
from django.db import models

class Student(models.Model):
    name = models.CharField(null=False, max_length=50)
    batch = models.CharField(null=False, max_length=50)
    roll_no = models.IntegerField()
    def __str__(self):
        return self.name
    
class Audio(models.Model):
    student_roll = models.IntegerField()
    audiofile=models.FileField(upload_to="documents/")
    
class Attendance(models.Model):
    student_atnd = models.ForeignKey(Student, on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now=True)
    batch = models.CharField(null=False,default="", max_length=50)
    course=models.CharField(null=False, max_length=50)
    teacher=models.CharField(null=False, max_length=50)
    

src/AudioProcessing/forms.py
from .models import *
from django import forms
from django.forms import ModelForm


class Studentform(forms.ModelForm):
    class Meta:
        model=Student
        fields='__all__'

src/AudioProcessing/views.py
import os
from django.conf import settings
from django.shortcuts import render,redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import *
import base64
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import csv
from .helper import *

def my_view(request):
    cur_user = request.user
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/dashboard")
        else:
            print("none")
    return render(request, "AudioProcessing/login.html")

@login_required()
def logout_view(request):
    if request.method=="POST":
        logout(request)
        return redirect("/login")
    return render(request, "AudioProcessing/logout.html")
    
@login_required()
def record(request):
    return render(request, "AudioProcessing/index.html")

def dashboard(request):
    cur_user = request.user
    if request.method == "POST":
        course = request.POST["course"]
        batch = request.POST["batch"]
        date = request.POST["date"]

        dates = Attendance.objects.filter(course=course, date__contains=date, batch=batch.upper())
        print(dates)

        file = open("filename.csv", "w")
        file.truncate()
        writer = csv.writer(file)

        head2=['Name','roll','date']
        writer.writerow(head2)
        for i in dates:
            date=[i.student_atnd.name, i.student_atnd.roll_no, i.date]
            print(date)
            writer.writerow(date)
        file.close()

        file_path = "filename.csv"
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'attachment; filename=' + f"{batch}_{course}.csv"
            return response

    return render(request, "AudioProcessing/dashboard.html")

@csrf_exempt
def save(request):
    curuser=request.user;
    if request.method == "POST":

        # details
        course = request.POST["course"]
        batch = request.POST["batch"]
        teacher = request.POST["teacher"]

        # array of base64 string
        audio = request.POST["audio"]
        audio = audio.split(",")[1]

        path = "./media/new_file.wav"
        audio_data = base64.urlsafe_b64decode(audio)

        # # saving the file
        audio_file = open(path, 'wb')
        audio_file.write(audio_data)

        # predicting student
        roll = predict_speaker(path)
        print(roll)

        student = Student.objects.filter(roll_no=roll[0])
        print(student)
        attendence_obj = Attendance.objects.create(student_atnd=student[0], teacher=str(teacher), course=course, batch=batch.upper())
        attendence_obj.save()

        return JsonResponse({"response": "Attendence Marked", "res": str(roll[0])})

@csrf_exempt          
def Student_reg(request):
    if request.method=="POST":

        # array of base64 string
        audios = request.POST.getlist("audio[]")

        # Student Details
        name=(request.POST.getlist("name")[0])
        batch=request.POST.getlist("batch")[0]
        rollno=request.POST.getlist("roll_no")[0]
        newstudent=Student.objects.create(name=name, batch=batch, roll_no=rollno)
        newstudent.save()
        i = 0
        
        for audio in audios:

            audio_data=base64.b64decode(audio)
            # saves the file in <student_id>__<roll_no>__<name>__<file_number>.mp3 format
            string1="newsrc/" + str(newstudent.id) + "__" + str(rollno)+ "__" + str(name) + "__" + str(i) + '.wav'
            i += 1
            print(string1)

            # saving the file
            with open(string1,'wb') as aud:
                aud.write(audio_data)
            audioobj = Audio.objects.create(student_roll=rollno, audiofile=string1)
            audioobj.save
    return render(request,"AudioProcessing/student.html")

src/AudioProcessing/templates/AudioProcessing/audio.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type='submit'>submit</button>
</form>

src/AudioProcessing/templates/AudioProcessing/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<style>
    * {
        padding: 0;
        margin: 0;
    }

    .main {
        background: #23344E;
        display: grid;
        place-items: center;
        height: 100vh;
        width: 100%;
    }

    form {
        display: flex;
        flex-direction: column;
        background-color: #E6EBF5;
        padding: 40px 40px 60px 40px;
        font-family: 'Roboto', sans-serif;
        font-size: 12px;
        border-radius: 5px;
        box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
    }

    label {
        margin-bottom: 8px
    }

    .box {
        margin-bottom: 20px;
        width: 290px;
        padding: 10px;
        border: #23344E 1px solid;
        background-color: #E6EBF5;
    }

    .date {
        width: 268px;
    }

    .dwn {
        padding: 10px 0;
        border: none;
        color: #E6EBF5;
        background: #23344E;
        box-shadow: rgba(0, 0, 0, 0.1) 0px 20px 25px -5px, rgba(0, 0, 0, 0.04) 0px 10px 10px -5px;
        font-family: 'Roboto', sans-serif;
        font-size: 12px;
    }

    .atnd {
        position: absolute;
        left: 50%;
        top: 88%;
        transform: translate(-50%, -88%);
        text-decoration: none;
        background-color: #E6EBF5;
        padding: 15px 30px;
        font-size: 13px;
        color: #23344E;
        box-shadow: rgba(0, 0, 0, 0.1) 0px 20px 25px -5px, rgba(0, 0, 0, 0.04) 0px 10px 10px -5px;
        font-family: 'Roboto', sans-serif;
    }

    h3 {
        color: #23344E;
        font-size: 17px;
        margin-bottom: 23px;
    }
</style>

<body>
    <div class="main">
        <form action="{% url 'dashboard' %}" method="POST">
            {% csrf_token %}
            <h3>Class Details</h3>
            <label for="batch">Batch</label>
            <select name="batch" id="batch" class="box">
                <option value="cse1">CSE 1</option>
                <option value="cse2">CSE 2</option>
                <option value="cse3">CSE 3</option>
                <option value="cse4">CSE 4</option>
            </select>
            <label for="course">Course</label>
            <select name="course" id="course" class="box">
                <option value="daa">DAA</option>
                <option value="pcd">PCD</option>
                <option value="ai">AI</option>
                <option value="dm">DM</option>
                <option value="ml">ML</option>
            </select>
            <label for="date">Date</label>
            <input type="date" name="date" id="date" class="date box">
            <button type='submit' class="dwn">Download</button>
        </form>
    </div>
    <a href="{% url 'record' %}" class="atnd">Schedule Attendance</a>
</body>

</html>

src/AudioProcessing/templates/AudioProcessing/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Speaker
{% endblock title %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'AudioProcessing/styles.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
{% endblock styles %}

{% block content %}
    <div class="hero">
        <div class="heading">
            <h1>Language Independent Speaker Indentification System</h1>
            <div class="lecture">
                <select name="batch" id="batch">
                    <option value="cse1">CSE 1</option>
                    <option value="cse2">CSE 2</option>
                    <option value="cse3">CSE 3</option>
                    <option value="cse4">CSE 4</option>
                    <option value="cse5">CSE 5</option>
                </select>
                <select name="course" id="course">
                    <option value="acdl">ACDL</option>
                    <option value="ml">ML</option>
                    <option value="daa">DAA</option>
                    <option value="dm">DM</option>
                    <option value="ai">AI</option>
                    <option value="pcd">PCD</option>
                </select>
                <select name="teacher" id="teacher">
                    <option value="shahin_makubhai">Prof. Shahin Makubhai</option>
                    <option value="rajesh_prasad">Dr. Rajesh Prasad</option>
                    <option value="nilima_kulkarni">Prof. Nilima Kulkarni</option>
                    <option value="digambar_patil">Prof. Digambar Patil</option>
                </select>
            </div>
        </div>
        <div class="record">
            <div class="audio" id="audio"></div>
                <button id="record" class="btn">
                    <i class='bx bx-microphone'></i>
                    <p>Record Audio</p>
                </button>
        </div>
    </div>
    {% comment %} {% if user.is_authenticated %}
    <a href="/logout">logout</a>
    {% else %}
    not loged in
    {% endif %} {% endcomment %}
{% endblock content %}

src/AudioProcessing/templates/AudioProcessing/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap');
        *{
            margin:0;
            padding:0;
        }
        body{
            background:#23344E;
            display:grid;
            place-items:center;
            height:100vh;
        }
        form
        {
            display:flex;
            flex-direction:column;
            width:300px;
            background:#fff;
            padding:60px 40px;
            font-family: 'Roboto', sans-serif;
            font-size: 13px;
            border-radius:5px;
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        }
        label
        {
            margin-bottom:8px
        }
        .box
        {
            margin-bottom:20px;
            padding:10px;
            border-radius:4px;
            border:#23344E 1px solid;
        }
        span
        {
            margin-bottom:20px;
        }
        button
        {
            padding:10px 0;
            border:none;
            color:#E6EBF5;
            background:#23344E;
            border-radius:5px;
            box-shadow: rgba(0, 0, 0, 0.1) 0px 20px 25px -5px, rgba(0, 0, 0, 0.04) 0px 10px 10px -5px;
        }
        .sp
        {
            margin-bottom:20px;
            display: flex;
            align-items: center;

        }
        #showPassword
        {
            margin-right:5px;
        }
    </style>
    <body>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="username">Name</label>
            <input type="text" name="username" id="username"/ class="box">
            <label for="password">Password</label>
            <input type="password" id="password" name="password"/ class="box">
            <div class="sp">
            <input type="checkbox" id="showPassword" >
            Show password
            </div>
            <button type='submit'>Sign in</button>
        </form>
        <script>
            document.getElementById('showPassword').onclick = function() {
                if ( this.checked ) {
                   document.getElementById('password').type = "text";
                } else {
                   document.getElementById('password').type = "password";
                }
            };
        </script>
    </body>
</html>

src/AudioProcessing/templates/AudioProcessing/logout.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <button type='submit'>logout</button>
</form>

src/AudioProcessing/templates/AudioProcessing/student.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    {% block styles %}{% endblock styles %}
</head>
<body>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}

        <input type="text" name="name" id="id_name" placeholder="name">
        <input type="text" name="batch" id="id_batch" placeholder="batch">
        <input type="text" name="roll_no" id="id_roll_no" placeholder="roll no">
    
        <div class="record">
            <div class="audio" id="audio"></div>
                <button id="record" class="btn">
                    <i class='bx bx-microphone'></i>
                    <p>Record Audio</p>
                </button>
            </div>
        </div>
        <hr>
        <button id="submit_btn">Submit</button>
    </form>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static "AudioProcessing/student_registration.js" %}"></script>
</html>
        

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    {% block styles %}{% endblock styles %}
</head>
<body>
    {% block content %}{% endblock content %}
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static "AudioProcessing/index.js" %}"></script>
</html>